(* ::Package:: *)

(* ::Input:: *)
(*g=980.0;*)
(*Subscript[h, 0]=2.5;*)
(*Subscript[h, g]=1.5;*)
(*a=10.0;*)
(**)
(*f=5.0;*)
(**)
(*\[Omega] = 2*\[Pi]*f;*)
(*RelDisp[k_,h_]=\[Omega]^2+g*k*Tan[k*h];*)
(**)
(*k0 = FindRoot[RelDisp[k,Subscript[h, 0]],{k,(\[Omega]*I)/(\[Sqrt](g*Subscript[h, 0]))}];*)
(*ComplexPlot[RelDisp[k,Subscript[h, 0]],{k,-3-3I,+3+3I}]*)
(*Subscript[k, 0]=Im[k/.k0[[1]]]*)
(**)
(**)
(*kg=FindRoot[RelDisp[k,Subscript[h, g]],{k,(\[Omega]*I)/(\[Sqrt](g*Subscript[h, g]))}];*)
(*ComplexPlot[RelDisp[k,Subscript[h, g]],{k,-3-3I,+3+3I}]*)
(*Subscript[k, g]=Im[k/.kg[[1]]]*)
(**)
(**)
(*Subscript[\[Lambda], g][\[Beta]_] :=1/(\[Sqrt](Subscript[k, g]^2-\[Beta]^2));*)
(*Subscript[\[Lambda], 0][\[Beta]_]:=1/(\[Sqrt](\[Beta]^2-Subscript[k, 0]^2));*)
(*EqBeta[\[Beta]_]:=(1/Subscript[\[Lambda], g][\[Beta]])*Tan[a/(2*Subscript[\[Lambda], g][\[Beta]])]-1/Subscript[\[Lambda], 0][\[Beta]];*)
(*beta = FindRoot[EqBeta[x],{x,Subscript[k, 0],Subscript[k, g]}];*)
(*\[Beta]=x/.beta[[1]]*)
(**)
(**)
(*Subscript[J, \[Alpha]_][k_, x_]:=BesselJ[\[Alpha],k*x];*)
(*Subscript[Y, \[Alpha]_][k_,x_]:=BesselY[\[Alpha],k*x];*)
(*Subscript[H, \[Alpha]_][k_,x_]:=HankelH1[\[Alpha],k*x];*)
(*Subscript[DJ, \[Alpha]_][k_,x_]:=k*(Subscript[J, \[Alpha]-1][k,x]-(\[Alpha]/(k*x))*Subscript[J, \[Alpha]][k,x]);*)
(*Subscript[DY, \[Alpha]_][k_,x_]:=k*(Subscript[Y, \[Alpha]-1][k,x]-(\[Alpha]/(k*x))*Subscript[Y, \[Alpha]][k,x]);*)
(*Subscript[DH, \[Alpha]_][k_,x_]:=k*(Subscript[H, \[Alpha]-1][k,x]-(\[Alpha]/(k*x))*Subscript[H, \[Alpha]][k,x]);*)
(**)
(**)
(*EqAlpha[\[Alpha]_,b_,c_]:=(Subscript[J, \[Alpha]][Subscript[k, 0],b]*Subscript[DJ, \[Alpha]][Subscript[k, g],b]-Subscript[DJ, \[Alpha]][Subscript[k, 0],b]*Subscript[J, \[Alpha]][Subscript[k, g],b])*(Subscript[H, \[Alpha]][Subscript[k, g],c]*Subscript[DH, \[Alpha]][Subscript[k, 0],c]-Subscript[H, \[Alpha]][Subscript[k, 0],c]*Subscript[DH, \[Alpha]][Subscript[k, g],c])-(Subscript[DJ, \[Alpha]][Subscript[k, 0],b]*Subscript[H, \[Alpha]][Subscript[k, g],b]-Subscript[J, \[Alpha]][Subscript[k, 0],b]*Subscript[DH, \[Alpha]][Subscript[k, g],b])*(Subscript[DJ, \[Alpha]][Subscript[k, g],c]*Subscript[H, \[Alpha]][Subscript[k, 0],c]-Subscript[J, \[Alpha]][Subscript[k, g],c]*Subscript[DH, \[Alpha]][Subscript[k, 0],c]);*)
(**)
(*A = {};*)
(*B = {};*)
(*\[CapitalDelta] = 10;*)
(*b= Range[5.0,100.0,2.5];*)
(*c=b+\[CapitalDelta];*)
(*Length[b]*)
(**)
(*Do[{alpha=FindRoot[EqAlpha[x,b[[i]],c[[i]]],{x,c[[i]]*Subscript[k, g]+0.1I}], AppendTo[A,Re[x/.alpha[[1]]]],AppendTo[B,Im[x/.alpha[[1]]]]},{i,Length[b]}]*)
(*A*)
(*B*)
(**)
(**)
(**)


(* ::Input:: *)
(**)


(* ::Input:: *)
(**)


(* ::Input:: *)
(**)
